-- V1 - cria tabelas oficina e maquina
CREATE TABLE oficina (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome VARCHAR(255) NOT NULL,
  local VARCHAR(255)
);

CREATE TABLE maquina (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  modelo VARCHAR(255) NOT NULL,
  status VARCHAR(50),
  oficina_id BIGINT,
  CONSTRAINT fk_oficina FOREIGN KEY (oficina_id) REFERENCES oficina(id)
);
